web1:
  image:
    repository: nginx
    tag: 1.21.6
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  ingress:
    enabled: true

web2:
  image:
    repository: nginx
    tag: 1.22.0
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  ingress:
    enabled: true