apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app.kubernetes.io/instance: multi-env-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: debug-sidecar
        deployah.dev/component: debug-sidecar
        deployah.dev/environment: dev
        deployah.dev/project: multi-env
        helm.sh/chart: debug-sidecar-0.1.0
    name: multi-env-dev-debug-sidecar
    namespace: default
spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app.kubernetes.io/instance: multi-env-dev
            app.kubernetes.io/name: debug-sidecar
    strategy:
        type: RollingUpdate
    template:
        metadata:
            annotations: null
            labels:
                app.kubernetes.io/instance: multi-env-dev
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: debug-sidecar
                deployah.dev/component: debug-sidecar
                deployah.dev/environment: dev
                deployah.dev/project: multi-env
                helm.sh/chart: debug-sidecar-0.1.0
        spec:
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - podAffinityTerm:
                            labelSelector:
                                matchLabels:
                                    app.kubernetes.io/instance: multi-env-dev
                                    app.kubernetes.io/name: debug-sidecar
                            topologyKey: kubernetes.io/hostname
                          weight: 1
            containers:
                - image: ghcr.io/acme/debug:1.0.0
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 6
                    periodSeconds: 10
                    tcpSocket:
                        port: http
                    timeoutSeconds: 3
                  name: debug-sidecar
                  ports:
                    - containerPort: 9000
                      name: http
                      protocol: TCP
                  readinessProbe:
                    failureThreshold: 3
                    periodSeconds: 5
                    tcpSocket:
                        port: http
                    timeoutSeconds: 3
                  resources:
                    limits: {}
                    requests:
                        cpu: 100m
                        ephemeral-storage: 50Mi
                        memory: 128Mi
                  startupProbe:
                    failureThreshold: 36
                    periodSeconds: 5
                    tcpSocket:
                        port: http
                    timeoutSeconds: 3
            restartPolicy: Always
            serviceAccountName: default
