version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - kind/chore
      - area/ci
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"
      osv-scanner-action:
        patterns:
          - "google/osv-scanner-action*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - kind/chore
      - area/ci

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - kind/chore
      - area/ci
