apiVersion: example.com/v1
kind: ClusterWidget
metadata:
    annotations:
        deployah.dev/project: extras-env-and-crds
        deployah.dev/source: manifests
    labels:
        deployah.dev/environment: dev
        deployah.dev/project: extras-env-and-crds
    name: shared-widget
spec: {}
