apiVersion: v1
data:
    note: extra-manifest-independent-of-crd
kind: ConfigMap
metadata:
    annotations:
        deployah.dev/environment-instance: dev
        deployah.dev/project: extras-env-and-crds
        deployah.dev/source: manifests
    labels:
        deployah.dev/environment: dev
        deployah.dev/instance: extras-env-and-crds-dev
        deployah.dev/project: extras-env-and-crds
    name: shared-widget
    namespace: default
