apiVersion: batch/v1
kind: CronJob
metadata:
    annotations:
        deployah.dev/project: longnameproj
        deployah.dev/source: spec
    labels:
        app.kubernetes.io/instance: longnameproj-review-feature-add-new-checkout-flow
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cleanup
        deployah.dev/component: cleanup
        deployah.dev/environment: review-feature-add-new-checkout-flow
        deployah.dev/project: longnameproj
        helm.sh/chart: cleanup-0.1.0
    name: longnameproj-review-feature-add-new-che-c287-cleanup
    namespace: default
spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 3
    jobTemplate:
        spec:
            activeDeadlineSeconds: 3600
            backoffLimit: 3
            completionMode: Indexed
            completions: 1
            parallelism: 1
            template:
                metadata:
                    labels:
                        app.kubernetes.io/instance: longnameproj-review-feature-add-new-checkout-flow
                        app.kubernetes.io/managed-by: Helm
                        app.kubernetes.io/name: cleanup
                        deployah.dev/component: cleanup
                        deployah.dev/environment: review-feature-add-new-checkout-flow
                        deployah.dev/project: longnameproj
                        helm.sh/chart: cleanup-0.1.0
                spec:
                    automountServiceAccountToken: false
                    containers:
                        - command:
                            - cleanup
                          image: docker.io/library/nginx:latest
                          imagePullPolicy: Always
                          name: cleanup
                          resources:
                            limits: {}
                            requests:
                                cpu: 500m
                                ephemeral-storage: 50Mi
                                memory: 512Mi
                    restartPolicy: OnFailure
    schedule: 0 3 * * *
    successfulJobsHistoryLimit: 3
    suspend: false
    timeZone: Etc/UTC
