apiVersion: v1
kind: Service
metadata:
    annotations:
        deployah.dev/project: longnameproj
        deployah.dev/source: spec
    labels:
        app.kubernetes.io/instance: longnameproj-review-feature-add-new-checkout-flow
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: api
        deployah.dev/component: api
        deployah.dev/environment: review-feature-add-new-checkout-flow
        deployah.dev/project: longnameproj
        helm.sh/chart: api-0.1.0
    name: longnameproj-review-feature-add-new-checkout-flow-api
    namespace: default
spec:
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
    selector:
        app.kubernetes.io/instance: longnameproj-review-feature-add-new-checkout-flow
        app.kubernetes.io/name: api
    sessionAffinity: None
    type: ClusterIP
