apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        deployah.dev/project: worker-stateless
        deployah.dev/source: spec
    labels:
        app.kubernetes.io/instance: worker-stateless-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: worker
        deployah.dev/component: worker
        deployah.dev/environment: dev
        deployah.dev/project: worker-stateless
        helm.sh/chart: worker-0.1.0
    name: worker-stateless-dev
    namespace: default
spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app.kubernetes.io/instance: worker-stateless-dev
            app.kubernetes.io/name: worker
    strategy:
        type: RollingUpdate
    template:
        metadata:
            annotations: null
            labels:
                app.kubernetes.io/instance: worker-stateless-dev
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: worker
                deployah.dev/component: worker
                deployah.dev/environment: dev
                deployah.dev/project: worker-stateless
                helm.sh/chart: worker-0.1.0
        spec:
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - podAffinityTerm:
                            labelSelector:
                                matchLabels:
                                    app.kubernetes.io/instance: worker-stateless-dev
                                    app.kubernetes.io/name: worker
                            topologyKey: kubernetes.io/hostname
                          weight: 1
            containers:
                - args:
                    - infinity
                  command:
                    - sleep
                  image: docker.io/library/busybox:1.36
                  imagePullPolicy: IfNotPresent
                  name: worker
                  resources:
                    limits: {}
                    requests:
                        cpu: 500m
                        ephemeral-storage: 50Mi
                        memory: 512Mi
            restartPolicy: Always
            serviceAccountName: default
            terminationGracePeriodSeconds: 60
