apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      environment: production
      deployah.dev/environment: production
    includeSelectors: false
images:
  - name: nginx
    newName: nginx
    newTag: "1.26"
replicas:
  - name: web
    count: 1
commonAnnotations:
  deployah.dev/source: spec
  deployah.dev/project: web
resources:
  - ../../base
  - ingress.yaml
