apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/version: "1.26"
    deployah.dev/project: web
    deployah.dev/component: web
    deployah.dev/environment: production
  annotations:
    deployah.dev/source: spec
    deployah.dev/project: web
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: web
        app.kubernetes.io/version: "1.26"
        deployah.dev/project: web
        deployah.dev/component: web
        deployah.dev/environment: production
      annotations:
        deployah.dev/source: spec
        deployah.dev/project: web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: web
                    app.kubernetes.io/instance: web
      containers:
        - name: web
          image: nginx:1.26
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 36
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 50Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
