apiVersion: v1
kind: Service
metadata:
    annotations:
        deployah.dev/project: stateful-hpa
        deployah.dev/source: spec
    labels:
        app.kubernetes.io/instance: stateful-hpa-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cache
        deployah.dev/component: cache
        deployah.dev/environment: dev
        deployah.dev/project: stateful-hpa
        helm.sh/chart: cache-0.1.0
    name: stateful-hpa-dev-cache-headless
    namespace: default
spec:
    clusterIP: None
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
    publishNotReadyAddresses: true
    selector:
        app.kubernetes.io/instance: stateful-hpa-dev
        app.kubernetes.io/name: cache
    type: ClusterIP
