apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    labels:
        app.kubernetes.io/instance: expose-secretname-production
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: api
        deployah.dev/component: api
        deployah.dev/environment: production
        deployah.dev/project: expose-secretname
        helm.sh/chart: api-0.1.0
    name: expose-secretname-production-api
    namespace: default
spec:
    rules:
        - host: api.example.com
          http:
            paths:
                - backend:
                    service:
                        name: expose-secretname-production-api
                        port:
                            name: http
                  path: /
                  pathType: ImplementationSpecific
    tls:
        - hosts:
            - api.example.com
          secretName: wildcard-example-com-tls
