apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/instance: health-disabled-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: api
        deployah.dev/component: api
        deployah.dev/environment: dev
        deployah.dev/project: health-disabled
        helm.sh/chart: api-0.1.0
    name: health-disabled-dev-api
    namespace: default
spec:
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: http
    selector:
        app.kubernetes.io/instance: health-disabled-dev
        app.kubernetes.io/name: api
    sessionAffinity: None
    type: ClusterIP
