apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/version: "1.26"
    deployah.dev/project: web
    deployah.dev/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
