{{- define "deployah.tls.selfsigned" -}}
{{- if .Values.ingress.enabled }}
{{- if and .Values.ingress.tls .Values.ingress.selfSigned (not .Values.ingress.secrets) }}
{{- $secretName := include "common.tplvalues.render" (dict "value" (printf "%s-tls" .Values.ingress.hostname) "context" $) }}
{{- $existing := lookup "v1" "Secret" (include "common.names.namespace" .) $secretName }}
{{- if not $existing }}
{{- $ca := genCA "deployah-ca" 3650 }}
{{- $cert := genSignedCert (include "common.tplvalues.render" (dict "value" .Values.ingress.hostname "context" $)) nil (list .Values.ingress.hostname) 3650 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

