apiVersion: v1
data:
    scope: prod-only
kind: ConfigMap
metadata:
    annotations:
        deployah.dev/project: extras-env-and-crds
        deployah.dev/source: manifests
    labels:
        deployah.dev/environment: prod
        deployah.dev/project: extras-env-and-crds
    name: prod-extra
    namespace: default
